// Generated by CoffeeScript 1.3.3
(function() {
  var Spine, SubTest,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  Spine = require('spine');

  SubTest = (function(_super) {

    __extends(SubTest, _super);

    SubTest.configure('SubTest', 'text');

    function SubTest() {
      SubTest.__super__.constructor.apply(this, arguments);
    }

    return SubTest;

  })(Spine.Model);

  module.exports = SubTest;

}).call(this);
